apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bc16-frontend
  labels:
    app: bc-frontend
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: bc-frontend
  template:
    metadata:
      labels:
        app: bc-frontend
    spec:
      containers:
      - name: bc-frontend
        image: "{{ .Values.imagefrontend.repository }}:{{ .Values.imagefrontend.tag }}"
        ports:
          - name: http
            containerPort: 80
            protocol: TCP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-db
  labels:
    app: db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: "{{ .Values.imagepostgres.repository }}:{{ .Values.imagepostgres.tag }}"
        env:
          - name: POSTGRES_USER
            value: {{ .Values.secert1.Postgres_user }}
          - name: POSTGRES_PASSWORD
            value: {{ .Values.secert1.Postgres_passwd }} 
          - name: POSTGRES_DB
            value: {{ .Values.secert1.Postgres_db }}
        ports:
          - name: http
            containerPort: 5432
            protocol: TCP
       
---


apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bcjobs
  labels:
    app: jobs
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: jobs
  template:
    metadata:
      labels:
        app: jobs
    spec:
      containers:
      - name: jobs
        image: "{{ .Values.imagejobs.repository }}:{{ .Values.imagejobs.tag }}"
        env:
          - name: SPRING_DATASOURCE_URL
            value: {{ .Values.secert2.jobs_url }}
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.secert2.jobs_usr }} 
          - name: SPRING_DATASOURCE_PASSWORD
            value: {{ .Values.secert2.jobs_passwd }}
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: {{ .Values.secert2.jobs_update }}
        ports:
          - name: http
            containerPort: 8082
            protocol: TCP
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bcorg
  labels:
    app: org
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: org
  template:
    metadata:
      labels:
        app: org
    spec:
      containers:
      - name: org
        image: "{{ .Values.imageorg.repository }}:{{ .Values.imageorg.tag }}"
        env:
          - name: SPRING_DATASOURCE_URL
            value: {{ .Values.secert3.jobs_url }}
          - name: SPRING_DATASOURCE_USERNAME
            value: {{ .Values.secert3.jobs_usr }} 
          - name: SPRING_DATASOURCE_PASSWORD
            value: {{ .Values.secert3.jobs_passwd }}
          - name: SPRING_JPA_HIBERNATE_DDL_AUTO
            value: {{ .Values.secert3.jobs_update }}
        ports:
          - name: http
            containerPort: 8081
            protocol: TCP








































       
























